# Site settings
title: Wind and Emission Reduction Targets in Fossil-Fuel Alberta
email: repa@uvic.ca
description: > # this means to ignore newlines until "baseurl:"
  This is a repo for a research. It includes some codes we used for the research.
baseurl: "/wind" # the subpath of your site, e.g. /blog/
url: "http://uvic-repa.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  uvic-repa
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
